name: CI

on: [push]

jobs:
  test:
    name: Test Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 20
          - 22

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npm test

      # TODO Enable those lines below if you use a Redis cache, you'll also need to configure GitHub Repository Secrets
      # env:
      #   REDIS_HOST: ${{ secrets.REDIS_HOST }}
      #   REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      # - name: Build
      #   run: npm run build
